### ISSUE TITLE
Error with setup.py

### ISSUE THREAD

**Issue by louloufev** [cherab/compass#27]
I tried to manually install cherab.compass with the setup.py, but it showed an error.

Compiling cherab/compass/math/profile/electron.pyx because it changed.
[1/1] Cythonizing cherab/compass/math/profile/electron.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from raysect.core.math.function cimport Function1D
^
------------------------------------------------------------

cherab/compass/math/profile/electron.pxd:1:0: 'raysect/core/math/function/Function1D.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from raysect.core.math.function cimport Function1D

cdef class ModifiedTanhGaussian(Function1D):
                               ^
------------------------------------------------------------

cherab/compass/math/profile/electron.pxd:4:32: First base of 'ModifiedTanhGaussian' is not an extension type

I tried again by replacing the  "from raysect.core.math.function cimport Function1D" line with "from cherab.core.math.function cimport Function1D" and it worked. 

To be fair, I realized it is not a good solution yet because I can't seem to be able to import any function from cherab.compass despite the installation not showing any errors, so there might be something else I am doing wrong.

**Comment by Mateasek** [comment]
Thanks for reporting @louloufev 

The problem is caused by Raysect updating its function framework and this package master branch not being updated for some time. It was already fixed in the development branch, I merged it to master, so please update your local repository and try it again.

**Comment by louloufev** [comment]
Thank you very much for your help, and sorry again for not making the request correctly the first time.
I am sorry to bother you again, but I still have a problem and I don't know if it is from my side or else.
The installation goes through, but when I try to import function from cherab.compass like in the demos, it says it doesn't find the module cherab.compass.
I installed manually cherab, then cherab-compass, and I don't understand why it works for cherab.core and not for cherab.compass.
I am using anaconda, is the problem coming from there ?

Thanks for your help,

Louis Fevre
________________________________
De : Matej Tomes ***@***.***>
Envoyé : jeudi 7 septembre 2023 13:26
À : cherab/compass ***@***.***>
Cc : louloufev ***@***.***>; Mention ***@***.***>
Objet : Re: [cherab/compass] Error with setup.py (Issue #27)


Thanks for reporting @louloufev<https://github.com/louloufev>

The problem is caused by Raysect updating its function framework and this package master branch not being updated for some time. It was already fixed in the development branch, I merged it to master, so please update your local repository and try it again.

**Comment by Mateasek** [comment]
Could you please paste exactly what you are doing and what the error output is? 

Are you running it on any of the COMPASS computers?
What module did you load?
What version of Raysect are you using?

**Comment by louloufev** [comment]
Yes, thank you, I will give more details.
I am a french phd student, working with Nicolas Lemoine and Jordan Cavalier on the fast camera and its tomographic inversion.

I usually work on the Compass computers using jupyter notebook, but there seems to be a conflict between cherab and jupyter that I can't explain.
I usually do this to work with the module pleque :
module load compass/dev
module load pleque/unstable

But when I try :
module load cherab
It doesn't want to launch jupyter. I tried with only module load cherab, but again it doesn't work.
Here is the error.


***@***.***:~$ module load cherab
Loading matlab-python-engine/2017a/3.5-anaconda
  ERROR: Requirement 'python/3.5-anaconda' is not loaded

Loading mdsplus-python/7-1-13/3.5-anaconda
  ERROR: Requirement 'python/3.5-anaconda' is not loaded

Loading compass/dev
  ERROR: Requirement 'python/3.5-anaconda' is not loaded
skip OpenADAS repo setup

Loading cherab/stable
  WARNING: Reload of dependent matlab-python-engine/2017a/3.5-anaconda failed
  WARNING: Reload of dependent mdsplus-python/7-1-13/3.5-anaconda failed
  WARNING: Reload of dependent compass/dev failed
***@***.***:~$ jupyter-notebook --ip="*" --no-browser --port=8222
Traceback (most recent call last):
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/notebook/notebookapp.py", line 864, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/sw/python2/anaconda3.7/lib/python3.7/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/python2/anaconda3.7/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</sw/python2/anaconda3.7/lib/python3.7/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/notebook/notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/notebook/notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/notebook/notebookapp.py", line 252, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/sw/python2/anaconda3.7/lib/python3.7/site-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/sw/python2/anaconda3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known


Seeing that it doesn't work on COMPASS computers, I tried it on my own computer.
I installed raysect version 0.7.1.
Then I installed manually cherab using python setup.py install --user (after downloading it on the git).
Then I did the same thing with cherab compass.
For cherab and raysect, there are no problems, but for cherab.compass, it doesn't find it.
When I list the packages, I see there is one named cherab-compass.

I hope there is enough information to see what is the problem.
Thank you again for your help, I am very struggling here.

Louis



________________________________
De : Matej Tomes ***@***.***>
Envoyé : jeudi 7 septembre 2023 20:35
À : cherab/compass ***@***.***>
Cc : louloufev ***@***.***>; Mention ***@***.***>
Objet : Re: [cherab/compass] Error with setup.py (Issue #27)


Could you please paste exactly what you are doing and what the error output is?

Are you running it on any of the COMPASS computers?
What module did you load?
What version of Raysect are you using?

**Comment by Mateasek** [comment]
This is not issue of the package but of the environment. I will contact Jordan Cavalier and you directly to sort this out. I think we can close the issue here.
